linters:
  disable-all: false
  enable:
    - errorlint
    - goimports
    - misspell
    - nolintlint
    - predeclared
    - testifylint
    - unconvert
    - durationcheck
    - nilerr
    - whitespace
    - unparam
    - tagalign
    - stylecheck
    - gosec
    - perfsprint
    - nestif
    - noctx
    - prealloc
    - depguard
    - gocritic
    - bodyclose

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "ioutil is deprecated, use os or io instead"

  nestif:
    min-complexity: 5

run:
  timeout: 5m
  tests: true