name: Rebase dev onto main

on:
  push:
    branches:
      - main

jobs:
  rebase-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Checkout dev branch
      run: git checkout dev

    - name: Rebase dev onto main
      run: |
        git rebase origin/main

    - name: Push changes
      run: git push origin dev --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
